pipeline {
    agent {
      node {
        label 'slave2'
        }
    }
    tools {
        maven 'maven354' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
            stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
